# Generated by Django 4.2.9 on 2024-11-04 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'LOCKED'), (1, 'UNLOCKED')], default=1)),
                ('last_lock_date', models.DateTimeField(blank=True, null=True)),
                ('last_unlock_date', models.DateTimeField(blank=True, null=True)),
                ('last_task_duration', models.DurationField(blank=True, null=True)),
                ('periodic_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
        ),
    ]
