version: '3.3'
volumes:
  postgres_data:
  static_value:
  output_value:
  redis_data:
  elasticsearch_data:

networks:
  test:
    driver: bridge


services:

  pgbouncer:
    image: edoburu/pgbouncer:latest
    env_file:
      - ./.env
    ports:
      - 5432:5432
    environment:
      DATABASE_URL: 'postgresql://***:***@***:***/kaspi_parser'
      AUTH_TYPE: 'scram-sha-256'

  web:
    image: inarash/kaspi_parser
    restart: always
    depends_on:
      - pgbouncer
      - rabbitmq
      - redis
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=parser_kaspi.settings.release
    volumes:
      - static_value:/code/parser_kaspi/static/
      - output_value:/code/output/
      - ./parser_kaspi/logs.txt:/code/parser_kaspi/logs.txt
      - /var/log/irocket/:/logs/

  nginx:
    image: nginx:1.23.1-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - output_value:/var/html/output/
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - nginx

  celery_worker:
    image: inarash/kaspi_parser
    restart: always
    depends_on:
      - web
      - rabbitmq
    env_file:
      - ./.env
    volumes:
      - ./parser_kaspi/logs.txt:/code/parser_kaspi/logs.txt
      - output_value:/code/output/
      - /var/log/irocket/:/logs/
    command: bash -c 'export DJANGO_SETTINGS_MODULE="parser_kaspi.settings.release"; cd parser_kaspi; celery -A parser_kaspi worker -Q default --loglevel=DEBUG --autoscale=64,4'

  celery_beat:
    image: inarash/kaspi_parser
    restart: always
    depends_on:
      - celery_worker
      - rabbitmq
    env_file:
      - ./.env
    volumes:
      - ./celerybeat-schedule/:/code/celerybeat
    command: bash -c 'export DJANGO_SETTINGS_MODULE="parser_kaspi.settings.release"; cd parser_kaspi; celery -A parser_kaspi beat --loglevel=DEBUG'

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=bitnami
    volumes:
      - ./rabbitmq/advanced.config:/bitnami/rabbitmq/conf/advanced.config
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.2
    user: root
    depends_on:
      - elasticsearch
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/log/irocket/:/var/log/irocket/:ro
    command: filebeat -e --strict.perms=false
    networks:
      - test


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
      - "xpack.security.enabled=true"

    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - test
    restart: on-failure
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - "xpack.security.authc.http.enabled=false"
      - ELASTICSEARCH_USERNAME="kibana_system"
      - ELASTICSEARCH_PASSWORD="***"
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - test
