# Generated by Django 4.2.9 on 2024-01-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KaspiNewOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaspi_order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='id заказа в каспи')),
                ('kaspi_order_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='код заказа в каспи')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='дата заказа в каспи')),
                ('order_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='статус заказа')),
                ('notification_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='статус уведомления')),
                ('notification_time', models.DateTimeField(auto_now=True, verbose_name='время уведомления')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='номер телефона')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО клиента')),
                ('delivery_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='статус отправки сообщения')),
                ('client_answer', models.CharField(blank=True, max_length=100, null=True, verbose_name='ответ клиента')),
            ],
            options={
                'verbose_name': 'Новый заказ Kaspi',
                'verbose_name_plural': 'Новые заказы Kaspi',
            },
        ),
    ]
