# Generated by Django 4.2.9 on 2024-01-31 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaspi_token', models.CharField(blank=True, max_length=250, null=True, verbose_name='id аккаунта каспи')),
                ('whatsapp_token', models.CharField(blank=True, max_length=300, null=True, verbose_name='ватсап токен')),
                ('whatsapp_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='id аккаунта ватсап')),
                ('whatsapp_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='номер ватсап')),
            ],
            options={
                'verbose_name': 'Продавец Kaspi',
                'verbose_name_plural': 'Продавцы Kaspi',
            },
        ),
        migrations.RemoveField(
            model_name='kaspineworder',
            name='delivery_status',
        ),
        migrations.AddField(
            model_name='kaspineworder',
            name='merchant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchants', to='notifications.merchant', verbose_name='продавец'),
        ),
    ]
