# Generated by Django 4.2.9 on 2024-01-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_merchant_remove_kaspineworder_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='время создания записи'),
        ),
    ]
