# Generated by Django 4.2.9 on 2024-01-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_merchant_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaspineworder',
            name='delivery_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='статус отправки сообщения'),
        ),
    ]
