# Generated by Django 4.2.9 on 2024-02-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_kaspineworder_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='имя'),
        ),
    ]
