# Generated by Django 4.2.9 on 2024-02-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_merchant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='enabled',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='активирован'),
        ),
    ]
