# Generated by Django 4.2.9 on 2024-02-01 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_merchant_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kaspineworder',
            name='merchant_id',
        ),
        migrations.AddField(
            model_name='kaspineworder',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='notifications.merchant', verbose_name='продавец'),
        ),
    ]
