# Generated by Django 4.2.9 on 2024-02-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_remove_kaspineworder_merchant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='merchant_shop_link',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='ссылка на сайт'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='period_to_be_informed_within',
            field=models.IntegerField(blank=True, null=True, verbose_name='период инфор-ния клиента'),
        ),
    ]
