# Generated by Django 4.2.9 on 2024-02-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_merchant_merchant_shop_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='manager_whatsapp_number',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='номер менеджера'),
        ),
    ]
