# Generated by Django 4.2.9 on 2024-02-05 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_merchant_manager_whatsapp_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='название')),
                ('product_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='код продукта')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='категория')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='количество')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='цена')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='notifications.kaspineworder', verbose_name='заказ каспи')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
