# Generated by Django 4.2.9 on 2024-02-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_orderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='creation_date',
            field=models.DateTimeField(auto_created=True, verbose_name='время создания записи'),
        ),
    ]
