# Generated by Django 4.2.9 on 2024-02-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_alter_merchant_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='message_template_name',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='название шаблона'),
        ),
    ]
