# Generated by Django 4.2.9 on 2024-02-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_merchant_message_template_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='message_template_name',
        ),
        migrations.AddField(
            model_name='merchant',
            name='message_template_name_ask_for_comment',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='шаблон для отзывов'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='message_template_name_new_order',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='шаблон для новых заказов'),
        ),
    ]
