# Generated by Django 4.2.9 on 2024-02-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='communication_type',
            field=models.CharField(blank=True, choices=[('GREEN_API', 'Green Api'), ('WHATSAPP', 'Whatsapp Api')], max_length=250, null=True, verbose_name='тип коммуникации'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='green_api_instance_id',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='инстанс грин апи'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='green_api_token',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='токен грин апи'),
        ),
    ]
