# Generated by Django 4.2.9 on 2024-02-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_merchant_communication_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kaspineworder',
            name='delivery_status',
        ),
        migrations.AddField(
            model_name='kaspineworder',
            name='first_message_delivery_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='статус первого сообщения'),
        ),
        migrations.AddField(
            model_name='kaspineworder',
            name='second_message_delivery_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='статус второго сообщения'),
        ),
    ]
