# Generated by Django 4.2.9 on 2024-02-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_remove_kaspineworder_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaspineworder',
            name='first_message_sending_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время уведомления'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='auto_accepting',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='автопринятие заказов'),
        ),
    ]
