# Generated by Django 4.2.9 on 2024-02-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_kaspineworder_first_message_sending_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='auto_accepting',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='автопринятие заказов'),
        ),
    ]
