# Generated by Django 4.2.9 on 2024-02-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_alter_merchant_auto_accepting'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaspineworder',
            name='auto_accepted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='заказ автопринят ботом'),
        ),
    ]
