# Generated by Django 4.2.9 on 2024-04-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0019_kaspineworder_auto_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='period_to_be_informed_within',
        ),
        migrations.AddField(
            model_name='merchant',
            name='template_type',
            field=models.CharField(blank=True, choices=[('WITH_BUTTONS', 'с кнопками'), ('WITHOUT_BUTTONS', 'без кнопок')], max_length=250, null=True, verbose_name='тип шаблона'),
        ),
        migrations.AlterField(
            model_name='kaspineworder',
            name='second_message_delivery_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='статус второго сообщения'),
        ),
        migrations.AlterField(
            model_name='kaspineworder',
            name='first_message_delivery_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='статус первого сообщения'),
        ),
    ]
