# Generated by Django 4.2.9 on 2024-04-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0022_remove_merchant_period_to_be_informed_within_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='subscription_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='дни по подписке'),
        ),
    ]
