# Generated by Django 4.2.9 on 2024-04-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0023_merchant_subscription_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='subscription_date_start',
            field=models.DateField(blank=True, null=True, verbose_name='дата начала подписки'),
        ),
    ]
