# Generated by Django 4.2.9 on 2024-04-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0024_merchant_subscription_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='subscription_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='дата оконч-я подписки'),
        ),
    ]
