# Generated by Django 4.2.9 on 2024-04-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0025_merchant_subscription_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaspineworder',
            name='api_order_state',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='состояние заказа по АПИ'),
        ),
        migrations.AddField(
            model_name='kaspineworder',
            name='api_order_status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='статус заказа по АПИ'),
        ),
    ]
