# Generated by Django 4.2.9 on 2024-04-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0026_kaspineworder_api_order_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='category',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_code',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='код продукта'),
        ),
    ]
