# Generated by Django 4.2.9 on 2024-04-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0027_alter_orderproduct_category_alter_orderproduct_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='contact_number',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='телефон для связи'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='message_language',
            field=models.CharField(blank=True, choices=[('RU', 'русский'), ('KZ', 'казахский')], default='RU', max_length=250, null=True, verbose_name='язык'),
        ),
    ]
