# Generated by Django 4.2.9 on 2024-04-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0028_merchant_contact_number_merchant_message_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_mastercode',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='мастеркод продукта'),
        ),
    ]
