# Generated by Django 4.2.9 on 2024-04-23 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0028_merchant_contact_number_merchant_message_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='chat_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='id телеграм-чата'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='membership_status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='статус подключения'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_created=True, verbose_name='дата создания')),
                ('type', models.CharField(max_length=300, verbose_name='тип инвойса')),
                ('currency', models.CharField(default='KZT', max_length=10, verbose_name='тип инвойса')),
                ('amount', models.IntegerField(verbose_name='сумма')),
                ('status', models.CharField(default='draft', max_length=10, verbose_name='статус инвойса')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='notifications.merchant', verbose_name='продавец')),
            ],
            options={
                'verbose_name': 'Инвойс',
                'verbose_name_plural': 'Инвойсы',
            },
        ),
    ]
