# Generated by Django 4.2.9 on 2024-04-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0029_orderproduct_product_mastercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='category',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_code',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='код продукта'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_mastercode',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='мастеркод продукта'),
        ),
    ]
