# Generated by Django 4.2.9 on 2024-04-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0029_merchant_chat_id_merchant_membership_status_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='telegram_mode',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='режим сообщений в тг'),
        ),
    ]
