# Generated by Django 4.2.9 on 2024-04-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0030_merchant_telegram_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='время создания записи'),
        ),
    ]
