# Generated by Django 4.2.9 on 2024-04-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0031_alter_merchant_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='creation_date',
            field=models.DateTimeField(verbose_name='время создания записи'),
        ),
    ]
