# Generated by Django 4.2.9 on 2024-04-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0034_alter_invoice_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='сумма'),
        ),
    ]
