# Generated by Django 4.2.9 on 2024-04-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0035_alter_invoice_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='enabled',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='активирован'),
        ),
    ]
