# Generated by Django 4.2.9 on 2024-04-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0030_alter_orderproduct_category_alter_orderproduct_name_and_more'),
        ('notifications', '0036_alter_merchant_enabled'),
    ]

    operations = [
    ]
