# Generated by Django 4.2.9 on 2024-05-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0037_merge_20240426_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='green_api_settings',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='настройка грин апи'),
        ),
    ]
