# Generated by Django 4.2.9 on 2024-05-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0038_merchant_green_api_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='subscription_days',
            field=models.IntegerField(blank=True, default=30, null=True, verbose_name='дни по подписке'),
        ),
    ]
