# Generated by Django 4.2.9 on 2024-05-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0039_alter_merchant_subscription_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='message_template_name_new_order',
            field=models.CharField(blank=True, help_text='hhdfhshfasfh fdsfhasfdlksjaf fdasfjlkasfha fdsjkfla', max_length=350, null=True, verbose_name='шаблон для новых заказов'),
        ),
    ]
