# Generated by Django 4.2.9 on 2024-05-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0041_alter_merchant_message_template_name_new_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='green_api_message_text_new_order',
            field=models.CharField(blank=True, help_text='Сейчас я делаю задачу:  у менеджера магазинов можно было возможность изменить текст сообщения из админки(для грин апи). Данный момент в Мерчанте есть 2поле, шаблон для новых заказов и для отзыва они используется только ватсап апи.  Можно эти поли использовать для грин апи тоже или лучше создать новый поле?', max_length=450, null=True, verbose_name='техт для новых заказов грин апи'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='message_template_name_new_order',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='шаблон для новых заказов'),
        ),
    ]
