# Generated by Django 4.2.9 on 2024-05-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0042_merchant_green_api_message_text_new_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='green_api_message_text_new_order',
            field=models.CharField(blank=True, help_text='Сейчас я делаю задачу:  \nу менеджера магазинов можно было возможность изменить текст сообщения из \nадминки(для грин апи). Данный момент в Мерчанте есть 2поле, шаблон для новых заказов и для отзыва они используется только ватсап апи.  \nМожно эти поли использовать для грин апи тоже или лучше создать новый поле?', max_length=500, null=True, verbose_name='техт для новых заказов грин апи'),
        ),
    ]
