# Generated by Django 4.2.9 on 2024-05-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0044_alter_merchant_green_api_message_text_new_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='green_api_message_text_new_order',
            field=models.CharField(blank=True, help_text='Сейчас я делаю задачу:  <br>у менеджера магазинов можно было возможность изменить текст сообщения из <br>админки(для грин апи). Данный момент в Мерчанте есть 2поле, шаблон для новых заказов и <br>для отзыва они используется только ватсап апи.  <br>Можно эти поли использовать для грин апи тоже или лучше создать новый поле?', max_length=500, null=True, verbose_name='техт для новых заказов грин апи'),
        ),
    ]
