# Generated by Django 4.2.9 on 2024-05-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0045_alter_merchant_green_api_message_text_new_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='green_api_message_text_new_order',
            field=models.CharField(blank=True, help_text='Пример: Здравствуйте, {client_name}!\nСпасибо за заказ в магазине {merchant_name}\nВы заказали: {product_names}\nПлановая дата доставки: {planned_delivery_date}.\nДоставка будет осуществлена в указанную дату.\nНомер заказа: {kaspi_order_code}\nВ ближайшее время мы соберём заказ и отправим вам.\nХороших покупок!<br>', max_length=500, null=True, verbose_name='техт для новых заказов грин апи'),
        ),
    ]
