# Generated by Django 4.2.9 on 2024-05-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0046_alter_merchant_green_api_message_text_new_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='green_api_message_text_new_order',
            field=models.CharField(blank=True, help_text='Пример: Здравствуйте, {client_name}!\nСпасибо за заказ в магазине {merchant_name}\nВы заказали: {product_names}\nПлановая дата доставки: {planned_delivery_date}.\nДоставка будет осуществлена в указанную дату.\nНомер заказа: {kaspi_order_code}\nВ ближайшее время мы соберём заказ и отправим вам.\nХороших покупок!<br>{client_name} - имя покупателя<br>{merchant_name} - название вашего магазина<br>{product_names} - название купленных продуктов<br>{planned_delivery_date} - планируемая дата доставка<br>{kaspi_order_code} - код заказа каспи<br>\\n - новая строка<br>Все эти данные у нас есть, просто вам нужно будет указать где эти данные стоит. Каждый магазин может формировать свои шаблон для отправки своих клиентах.<br>Обязательно нужно сделать как в примере, чтобы правильно отправлять сообщения. Если где то будет ошибка или пустой используется шаблон как в примере.<br>', max_length=500, null=True, verbose_name='техт для новых заказов грин апи'),
        ),
    ]
