# Generated by Django 4.2.9 on 2024-05-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0051_alter_merchant_green_api_message_text_new_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='kaspi_shop_uid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='uid каспи магазин'),
        ),
    ]
