# Generated by Django 4.2.9 on 2024-05-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0052_merchant_kaspi_shop_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='type_of_subscription',
            field=models.CharField(choices=[('demo', 'Демо'), ('standard', 'Стандарт'), ('standard+', 'Стандарт+')], max_length=100, null=True, verbose_name='тип подписки'),
        ),
    ]
