# Generated by Django 4.2.9 on 2024-05-23 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0053_merchant_type_of_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='имя')),
                ('phone_number', models.CharField(max_length=350, null=True, verbose_name='телефон номер менеджера')),
            ],
        ),
        migrations.AddField(
            model_name='merchant',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchants', to='notifications.manager', verbose_name='менеджер'),
        ),
    ]
