# Generated by Django 4.2.9 on 2024-05-23 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0054_manager_merchant_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджеры'},
        ),
    ]
