# Generated by Django 4.2.9 on 2024-05-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0055_alter_manager_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='contact_number',
            field=models.CharField(max_length=350, null=True, verbose_name='телефон для связи'),
        ),
    ]
