# Generated by Django 4.2.9 on 2024-05-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0056_alter_merchant_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='green_api_review_with_confirm',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='отзыв green api с подтверждением'),
        ),
    ]
