# Generated by Django 4.2.9 on 2024-05-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0057_merchant_green_api_review_with_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaspineworder',
            name='first_message_sending_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время уведомления первого сообшения'),
        ),
    ]
