# Generated by Django 4.2.9 on 2024-05-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0058_alter_kaspineworder_first_message_sending_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='green_api_message_text_for_review',
            field=models.TextField(blank=True, help_text='Пример: Здравствуйте, {client_name}!\\nСпасибо за заказ в магазине {merchant_name}\\nВы заказали: {product_names}\\nПлановая дата доставки: {planned_delivery_date}.\\nДоставка будет осуществлена в указанную дату.\\nНомер заказа: {kaspi_order_code}\\nВ ближайшее время мы соберём заказ и отправим вам.\\nХороших покупок!<br><br>{client_name} - имя покупателя<br>{merchant_name} - название вашего магазина<br>{product_names} - название купленных продуктов<br>{planned_delivery_date} - планируемая дата доставка<br>{kaspi_order_code} - код заказа каспи<br>\\n - новая строка<br><br>Каждый магазин может формировать свои шаблон для отправки своих клиентах. Обязательно нужно исползовать все 5 данные, чтобы правильно отправлять сообщения.<br>Если шаблон пустой или где то будет ошибка, используется шаблон как в примере.<br>', null=True, verbose_name='шаблон текста для отзыва грин апи'),
        ),
    ]
