# Generated by Django 4.2.9 on 2024-05-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0060_alter_merchant_green_api_message_text_for_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='green_api_message_text_for_review',
            field=models.TextField(blank=True, help_text='Пример: Здравствуйте, {client_name}!\nПоздравляем с покупкой!\nМы надеемся, что вам все понравилось.\nЕсли вам не сложно, то оставьте отзыв здесь:\n {link}<br><br>{client_name} - имя покупателя<br>{link} - ссылка отзыва<br>\\n - новая строка<br><br>Если шаблон пустой или где то будет ошибка, используется шаблон как в примере.<br>', null=True, verbose_name='шаблон текста для отзыва грин апи'),
        ),
    ]
