# Generated by Django 4.2.9 on 2024-05-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0062_alter_merchant_green_api_message_text_for_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='autofill_green_api',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='auto fill green api'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='communication_type',
            field=models.CharField(choices=[('GREEN_API', 'Green Api'), ('WHATSAPP', 'Whatsapp Api')], max_length=250, null=True, verbose_name='тип коммуникации'),
        ),
    ]
