# Generated by Django 4.2.9 on 2024-05-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0063_merchant_autofill_green_api_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='uid',
            field=models.CharField(db_index=True, max_length=32, null=True, unique=True),
        ),
    ]
