# Generated by Django 4.2.9 on 2024-05-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0064_merchant_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='autofill_green_api',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='автоматическое заполнение грин апи'),
        ),
    ]
