# Generated by Django 4.2.9 on 2024-05-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0065_alter_merchant_autofill_green_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='green_api_qr_link',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='ссылка на QR грин апи'),
        ),
    ]
