# Generated by Django 4.2.9 on 2024-05-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0067_alter_merchant_type_of_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='type_of_subscription',
            field=models.CharField(choices=[('demo', 'Демо'), ('standard', 'Стандарт'), ('standard+', 'Стандарт+'), ('business', 'Бизнес')], max_length=100, null=True, verbose_name='тип подписки'),
        ),
    ]
