# Generated by Django 4.2.9 on 2024-05-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0068_alter_merchant_type_of_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaspineworder',
            name='is_delivery_to_postamat',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='доставка на постамат'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='send_messages_by_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='отправка сообщений по статусу'),
        ),
    ]
