# Generated by Django 4.2.9 on 2024-05-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0069_kaspineworder_is_delivery_to_postamat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaspineworder',
            name='planned_delivery_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='планируемая дата поставки'),
        ),
    ]
