# Generated by Django 4.2.9 on 2024-06-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0070_kaspineworder_planned_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='daily_message_counts',
            field=models.JSONField(default=dict, verbose_name='Ежедневные количества сообщений'),
        ),
    ]
