# Generated by Django 4.2.9 on 2024-06-03 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0071_merchant_daily_message_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='promo_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Промо-код'),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('cashback_days', models.IntegerField(default=5, verbose_name='Дни кэшбэка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.merchant', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Промо-код',
                'verbose_name_plural': 'Промо-коды',
            },
        ),
        migrations.CreateModel(
            name='Cashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(verbose_name='Дни')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashbacks', to='notifications.merchant', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Кэшбэк',
                'verbose_name_plural': 'Кэшбэки',
            },
        ),
    ]
