# Generated by Django 4.2.9 on 2024-06-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0072_merchant_promo_code_promocode_cashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='freeze_tariff',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='заморозкa тарифа'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='subscription_days',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name='дни по подписке'),
        ),
    ]
