# Generated by Django 4.2.9 on 2024-06-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0073_merchant_freeze_tariff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='message_template_name_ask_for_self_call',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='шаблон для самовызов'),
        ),
    ]
