# Generated by Django 4.2.9 on 2024-06-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0074_merchant_message_template_name_ask_for_self_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='имя')),
                ('kaspi_token', models.CharField(blank=True, max_length=250, null=True, verbose_name='id аккаунта каспи')),
                ('message_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='ид сообщения')),
                ('status_message', models.CharField(blank=True, max_length=100, null=True, verbose_name='статус уведомления')),
                ('notification_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='статус сообщение')),
            ],
            options={
                'verbose_name': 'Рассылки',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
