# Generated by Django 4.2.9 on 2024-06-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0075_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='green_api_instance_id',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='инстанс грин апи'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='green_api_token',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='токен грин апи'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='phone_number',
            field=models.CharField(max_length=350, null=True, verbose_name='телефон номер'),
        ),
    ]
