# Generated by Django 4.2.9 on 2024-07-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0076_mailing_green_api_instance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='send_first_message',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='отправить первое сообщение'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='send_second_message',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='отправить второе сообщение'),
        ),
    ]
