# Generated by Django 4.2.9 on 2024-07-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0077_merchant_send_first_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='second_message_delay',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='отправить второе сообщения с задержкой в минутах'),
        ),
    ]
