# Generated by Django 4.2.9 on 2024-07-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0079_alter_kaspineworder_first_message_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaspineworder',
            name='second_message_delivery_status',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='статус второго сообщения'),
        ),
    ]
