# Generated by Django 4.2.9 on 2024-07-23 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0080_alter_kaspineworder_second_message_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='имя'),
        ),
        migrations.CreateModel(
            name='ResendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='с какого число')),
                ('first_message_delivery_status', models.CharField(max_length=250, null=True, verbose_name='статус первого сообщения')),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.merchant', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Resend message',
                'verbose_name_plural': 'Resend message',
            },
        ),
    ]
