# Generated by Django 4.2.9 on 2024-07-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0081_alter_merchant_name_resendmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resendmessage',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='resendmessage',
            name='start_date',
            field=models.DateField(null=True, verbose_name='с какого число'),
        ),
    ]
