# Generated by Django 4.2.9 on 2024-07-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0082_remove_resendmessage_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resendmessage',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='статус'),
        ),
    ]
