# Generated by Django 4.2.9 on 2024-07-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0083_resendmessage_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resendmessage',
            options={'verbose_name': 'Переотправить сообщений', 'verbose_name_plural': 'Переотправить сообщений'},
        ),
        migrations.AddField(
            model_name='kaspineworder',
            name='is_kaspi_postamat',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
