# Generated by Django 4.2.9 on 2024-08-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0084_alter_resendmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='green_api_message_text_new_order',
            field=models.TextField(blank=True, help_text='Пример: <br>{hello_rus}, {client_name}!<br>Спасибо за заказ в магазине {merchant_name}<br>Вы заказали: {product_names}<br>Плановая дата доставки: {planned_delivery_date}.<br>Доставка будет осуществлена в указанную дату.<br>Номер заказа: {kaspi_order_code}<br>В ближайшее время мы соберём заказ и отправим вам.<br>Хороших покупок!<br><br><br>{hello_kaz} - Қайырлы таң, Қайырлы күн, Қайырлы кеш, Қайырлы түн (не обязательно)<br>{hello_rus} - Доброе утро, Добрый день, Добрый вечер, Доброй ночи (не обязательно)<br>{client_name} - имя покупателя (обязательно)<br>{merchant_name} - название вашего магазина (обязательно)<br>{product_names} - название купленных продуктов (обязательно)<br>{planned_delivery_date} - планируемая дата доставка (обязательно)<br>{kaspi_order_code} - код заказа каспи (обязательно)<br><br>Каждый магазин может формировать свои шаблон для отправки своих клиентах.<br>Если шаблон пустой или где то будет ошибка, используется шаблон как в примере.<br>', null=True, verbose_name='шаблон текста для новых заказов грин апи'),
        ),
    ]
