# Generated by Django 4.2.9 on 2024-08-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0085_alter_merchant_green_api_message_text_new_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='green_api_message_text_for_review',
            field=models.TextField(blank=True, help_text='Пример:<br>{hello_rus}, {client_name}!<br>Поздравляем с покупкой!<br>Мы надеемся, что вам все понравилось.<br>Если вам не сложно, то оставьте отзыв здесь:<br>{link}<br><br><br>{hello_kaz} - Қайырлы таң, Қайырлы күн, Қайырлы кеш, Қайырлы түн (не обязательно)<br>{hello_rus} - Доброе утро, Добрый день, Добрый вечер, Доброй ночи (не обязательно)<br>{client_name} - имя покупателя (обязательно)<br>{link} - ссылка отзыва (обязательно)<br>Если шаблон пустой или где то будет ошибка, используется шаблон как в примере.<br>', null=True, verbose_name='шаблон текста для отзыва грин апи'),
        ),
    ]
