# Generated by Django 4.2.9 on 2024-08-29 09:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0086_alter_merchant_green_api_message_text_for_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='uid',
            field=models.CharField(db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
