# Generated by Django 4.2.9 on 2024-08-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0087_alter_merchant_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='webhook_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Webhook URL'),
        ),
    ]
