# Generated by Django 4.2.9 on 2024-08-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0088_merchant_webhook_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='green_api_settings',
        ),
    ]
