# Generated by Django 4.2.9 on 2024-09-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0090_manager_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='user',
        ),
    ]
