# Generated by Django 4.2.9 on 2024-10-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0091_remove_manager_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='core_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='core id пользователя'),
        ),
    ]
