# Generated by Django 4.2.9 on 2024-11-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0092_customuser_core_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='execution_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=5, verbose_name='Тип (Для разработчиков)'),
        ),
    ]
