# Generated by Django 4.2.9 on 2024-11-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0093_merchant_execution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaspineworder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создание в нашей системе'),
        ),
    ]
