# Generated by Django 4.2.9 on 2024-11-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0094_kaspineworder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaspineworder',
            name='kaspi_order_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='код заказа в каспи'),
        ),
    ]
