# Generated by Django 4.2.9 on 2024-11-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0095_alter_kaspineworder_kaspi_order_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kaspineworder',
            options={'ordering': ('-id',), 'verbose_name': 'Новый заказ Kaspi', 'verbose_name_plural': 'Новые заказы Kaspi'},
        ),
    ]
