# Generated by Django 4.2.9 on 2024-12-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0096_alter_kaspineworder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaspineworder',
            name='kaspi_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='id заказа в каспи'),
        ),
    ]
