# Generated by Django 4.2.9 on 2025-02-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0099_merchant_green_api_message_text_for_postamat_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='green_api_message_text_for_postamat_order',
            field=models.TextField(blank=True, help_text='Пример:<br>{hello_rus}, {client_name}!<br>Ваш заказ с номером {kaspi_order_code} был успешно доставлен в Kaspi постомат.<br>Ваш товар: {product_names}<br>Не забудьте забрать его до автоматической отмены заказа.<br>Спасибо за покупку!<br><br><br>{hello_kaz} - Қайырлы таң, Қайырлы күн, Қайырлы кеш, Қайырлы түн (не обязательно)<br>{hello_rus} - Доброе утро, Добрый день, Добрый вечер, Доброй ночи (не обязательно)<br>{client_name} - имя покупателя (обязательно)<br>{kaspi_order_code} - код заказа каспи (обязательно)<br>{product_names} - название продуктов (обязательно)<br>Если шаблон пустой или где то будет ошибка, используется шаблон как в примере.<br>', null=True, verbose_name='шаблон текста для заказа в постомат'),
        ),
    ]
