# Generated by Django 4.2.11 on 2024-04-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='kaspi_token',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='токен каспи'),
        ),
    ]
