# Generated by Django 4.2.11 on 2024-04-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0002_merchant_kaspi_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaspiproduct',
            name='date_of_parsing',
            field=models.DateTimeField(auto_now=True, verbose_name='время парсинга'),
        ),
    ]
