# Generated by Django 4.2.11 on 2024-05-13 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KaspiNotificationClient',
        ),
        migrations.AlterModelOptions(
            name='merchant',
            options={'verbose_name': 'Магазин Kaspi', 'verbose_name_plural': 'Магазины Kaspi'},
        ),
        migrations.AddField(
            model_name='merchant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL, verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='kaspi_token',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='kaspi токен'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='login',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='kaspi логин'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='id магазина'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='название магазина'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='password',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='kaspi пароль'),
        ),
    ]
