# Generated by Django 4.2.11 on 2024-05-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0005_delete_kaspinotificationclient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='enabled',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='активирован'),
        ),
    ]
