# Generated by Django 4.2.11 on 2024-05-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0006_merchant_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='competitors_to_exclude',
            field=models.JSONField(default=[], verbose_name='исключить конкурентов'),
        ),
    ]
