# Generated by Django 4.2.11 on 2024-05-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0007_merchant_competitors_to_exclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='competitors_to_exclude',
            field=models.JSONField(blank=True, null=True, verbose_name='исключить конкурентов'),
        ),
    ]
