# Generated by Django 4.2.11 on 2024-05-27 05:33

from django.db import migrations, models
import parser_kaspi_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0010_alter_merchant_competitors_to_exclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='competitors_to_exclude',
            field=models.JSONField(blank=True, default=list, validators=[parser_kaspi_data.models.competitors_to_exclude_validator], verbose_name='исключить конкурентов'),
        ),
    ]
