# Generated by Django 4.2.11 on 2024-05-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0011_alter_merchant_competitors_to_exclude'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='merchant',
            constraint=models.UniqueConstraint(fields=('merchant_id',), name='unique_shop_id'),
        ),
    ]
