# Generated by Django 4.2.11 on 2024-05-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0012_merchant_unique_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='id магазина'),
        ),
    ]
