# Generated by Django 4.2.11 on 2024-05-27 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0013_alter_merchant_merchant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='рейтинг')),
                ('text', models.TextField(blank=True, null=True, verbose_name='текст комментария')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'Комментарий пользователей',
                'verbose_name_plural': 'Комментарии пользователей',
            },
        ),
    ]
