# Generated by Django 4.2.11 on 2024-05-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaspiproduct',
            name='max_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='максимальная цена'),
        ),
        migrations.AddField(
            model_name='kaspiproduct',
            name='min_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='минимальная цена'),
        ),
    ]
