# Generated by Django 4.2.11 on 2024-05-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0015_kaspiproduct_max_price_kaspiproduct_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaspiproduct',
            name='product_card_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ссылка на карточку товара'),
        ),
        migrations.AddField(
            model_name='kaspiproduct',
            name='product_image_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='фотография товара'),
        ),
    ]
