# Generated by Django 4.2.11 on 2024-05-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0016_kaspiproduct_product_card_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaspiproduct',
            name='recently_parsed',
            field=models.BooleanField(default=True, verbose_name='актуальный'),
        ),
    ]
