# Generated by Django 4.2.11 on 2024-06-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0017_kaspiproduct_recently_parsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='subscription_date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата оконч-я подписки'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='subscription_date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата начала подписки'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='subscription_days',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name='дни по подписке'),
        ),
    ]
