# Generated by Django 4.2.11 on 2024-06-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0017_kaspiproduct_recently_parsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='xml_file_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='xml-файл'),
        ),
    ]
