# Generated by Django 4.2.11 on 2024-06-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0018_merchant_subscription_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='used_trial',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='использованный пробный период'),
        ),
    ]
