# Generated by Django 4.2.11 on 2024-06-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0019_customuser_used_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='subscription_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='дни по подписке'),
        ),
    ]
