# Generated by Django 4.2.11 on 2024-06-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0020_alter_merchant_subscription_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='subscription_date_start',
            field=models.DateTimeField(blank=True, default=0, null=True, verbose_name='дата начала подписки'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='subscription_days',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='дни по подписке'),
        ),
    ]
