# Generated by Django 4.2.11 on 2024-06-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0021_alter_merchant_subscription_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='subscription_date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата начала подписки'),
        ),
    ]
