# Generated by Django 4.2.11 on 2024-06-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0022_alter_merchant_subscription_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='subscription_days',
            field=models.IntegerField(blank=True, default=0, verbose_name='дни по подписке'),
        ),
    ]
