# Generated by Django 4.2.11 on 2024-06-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0018_merchant_xml_file_path'),
        ('parser_kaspi_data', '0023_alter_merchant_subscription_days'),
    ]

    operations = [
    ]
