# Generated by Django 4.2.11 on 2024-06-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0024_merge_20240612_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата регистрации'),
        ),
    ]
