# Generated by Django 4.2.11 on 2024-06-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0025_merchant_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaspiproduct',
            name='num_checks_to_skip',
            field=models.IntegerField(default=0, verbose_name='кол-во пропусков цикла'),
        ),
        migrations.AddField(
            model_name='kaspiproduct',
            name='num_checks_without_changed_price',
            field=models.IntegerField(default=0, verbose_name='кол-во итераций без изм-я цены'),
        ),
        migrations.AddField(
            model_name='kaspiproduct',
            name='product_flag',
            field=models.CharField(choices=[('HOT', 'Hot'), ('WARM', 'Warm'), ('COLD', 'Cold')], default='Hot', verbose_name='ценовой флаг'),
        ),
    ]
