# Generated by Django 4.2.11 on 2024-06-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0025_merchant_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='informed_about_login_problems',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='информирован о проблемах с логином'),
        ),
    ]
