# Generated by Django 4.2.11 on 2024-06-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0026_kaspiproduct_num_checks_to_skip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaspiproduct',
            name='product_flag',
            field=models.CharField(default='Hot', max_length=100, verbose_name='ценовой флаг'),
        ),
    ]
