# Generated by Django 4.2.11 on 2024-06-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0027_alter_kaspiproduct_availabilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaspiproduct',
            name='availabilities',
            field=models.JSONField(blank=True, default=list, verbose_name='данные для xml-файла'),
        ),
    ]
