# Generated by Django 4.2.11 on 2024-06-26 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0026_customuser_informed_about_login_problems'),
        ('parser_kaspi_data', '0027_alter_kaspiproduct_product_flag'),
        ('parser_kaspi_data', '0028_alter_kaspiproduct_availabilities'),
    ]

    operations = [
    ]
