# Generated by Django 4.2.11 on 2024-06-26 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0029_merge_20240626_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='текст сообщения')),
                ('message_type', models.CharField(blank=True, choices=[('Info', 'Info'), ('Warning', 'Warning'), ('Critical', 'Critical')], max_length=10, null=True, verbose_name='тип сообщения')),
                ('message_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата сообщения')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'Сообщение пользователя',
                'verbose_name_plural': 'Сообщения пользователей',
            },
        ),
    ]
