# Generated by Django 4.2.11 on 2024-06-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0030_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='message_level',
            field=models.CharField(blank=True, choices=[('Info', 'Info'), ('Warning', 'Warning'), ('Critical', 'Critical')], max_length=10, null=True, verbose_name='уровень сообщения'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='message_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='тип сообщения'),
        ),
    ]
