# Generated by Django 4.2.11 on 2024-06-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0031_usernotification_message_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='message_text',
            field=models.TextField(blank=True, null=True, verbose_name='текст сообщения'),
        ),
    ]
