# Generated by Django 4.2.11 on 2024-07-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0033_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
