# Generated by Django 4.2.11 on 2024-07-17 09:25

from django.db import migrations
import parser_kaspi_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0034_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', parser_kaspi_data.models.CustomerUserManager()),
            ],
        ),
    ]
