# Generated by Django 4.2.11 on 2024-07-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0035_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='execution_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='B', max_length=5, verbose_name='Тип (A - если товаров много)'),
        ),
    ]
