# Generated by Django 4.2.11 on 2024-07-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0036_merchant_execution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='название магазина'),
        ),
    ]
