# Generated by Django 4.2.11 on 2024-07-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0037_alter_merchant_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['enable_parsing', 'enabled', 'execution_type'], name='parser_kasp_enable__cf9622_idx'),
        ),
    ]
