# Generated by Django 4.2.11 on 2024-08-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0038_merchant_parser_kasp_enable__cf9622_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kaspiproduct',
            options={'ordering': ['pk'], 'verbose_name': 'Продукт Kaspi', 'verbose_name_plural': 'Продукты Kaspi'},
        ),
        migrations.AlterField(
            model_name='kaspiproduct',
            name='master_sku',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='SKU продукта'),
        ),
    ]
