# Generated by Django 4.2.11 on 2024-08-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0039_alter_kaspiproduct_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='kaspiproduct',
            index=models.Index(fields=['master_sku', 'merchant_id'], name='parser_kasp_master__0c9057_idx'),
        ),
    ]
