# Generated by Django 4.2.11 on 2024-08-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0040_kaspiproduct_parser_kasp_master__0c9057_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='kaspiproduct',
            index=models.Index(fields=['price_auto_change', 'available', 'merchant_id', 'recently_parsed'], name='parser_kasp_price_a_24317e_idx'),
        ),
    ]
