# Generated by Django 4.2.11 on 2024-08-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0041_kaspiproduct_parser_kasp_price_a_24317e_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaspiproduct',
            name='recently_parsed',
            field=models.BooleanField(db_index=True, default=True, verbose_name='актуальный'),
        ),
    ]
