# Generated by Django 4.2.11 on 2024-10-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_kaspi_data', '0042_alter_kaspiproduct_recently_parsed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='date_of_changing',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время изменения'),
        ),
    ]
