# Generated by Django 4.2.11 on 2024-08-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=11)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CabinetLog',
            fields=[
                ('time', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=11)),
                ('message', models.TextField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('conversation_id', models.CharField(blank=True, max_length=32, null=True)),
                ('cabinet_cookie', models.TextField(blank=True, null=True)),
                ('method', models.CharField(db_index=True, max_length=128)),
                ('merchant_reference', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('status', models.IntegerField(choices=[(1, 'success'), (2, 'warning'), (3, 'error')], default=1)),
                ('response_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-pk'],
                'indexes': [models.Index(fields=['time'], name='logger_cabi_time_25059f_idx')],
            },
        ),
    ]
