# Generated by Django 4.2.11 on 2024-08-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetlog',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
